ter 17 set 2024 13:15:21 -04 Vilmar Catafesta (vcatafesta@gmail.com)

diff --git a/.github/workflows/void.yml b/.github/workflows/void.yml
--- a/.github/workflows/void.yml
+++ b/.github/workflows/void.yml
@@ -112,5 +112,53 @@ jobs:
           github_token: ${{ secrets.TOKEN_RELEASE }}
 
       - name: Set ISO path
-        run: echo "ISO_PATH=${{ env.WORK_PATH }}/${{ env.ISO_BASENAME }}" >> $GITHUB_ENV
+        run: |
+          echo "ISO_PATH=${{ env.WORK_PATH }}/${{ env.ISO_BASENAME }}" >> $GITHUB_ENV
+          echo "XZ_PATH=${{ env.WORK_PATH }}/${{ env.XZ_BASENAME }}" >> $GITHUB_ENV
+
+      - name: Calculate ISO MD5 Hash
+        shell: bash
+        run: |
+          echo "Calculating MD5 hash for ISO file..."
+          echo "ISO_PATH is: '${{ env.ISO_PATH }}'"
+          if [[ -f "${{ env.ISO_PATH }}" ]]; then
+            md5sum "${{ env.ISO_PATH }}" > "${{ env.ISO_PATH }}.md5"
+            echo "MD5 hash calculated and saved:"
+            cat "${{ env.ISO_PATH }}.md5"
+          else
+            echo "Error: ISO file not found at ${{ env.ISO_PATH }}"
+            exit 1
+          fi
+
+      - name: Prepare ISO for release
+        id: prepare-iso
+        shell: bash
+        run: |
+          ls -lh
+          release=$(basename "${{ env.ISO_PATH }}" .iso)
+          zip -j -0 -s 2000m ${release}.zip ${{ env.ISO_PATH }}
+          echo "release_name=${release}" >> $GITHUB_OUTPUT
+          echo "ISO prepared for release"
+
+      - name: Upload ISO as artifact
+        uses: actions/upload-artifact@v3
+        with:
+          name: ${{ steps.prepare-iso.outputs.release_name }}
+          path: |
+            ${{ env.ISO_PATH }}
+            ${{ env.ISO_PATH }}.md5
+            ${{ env.ISO_PATH }}.pkgs
+
+      - name: Create Release
+        if: ${{ (github.event.client_payload.manjaro_branch || inputs.manjaro_branch) == 'stable' && (github.event.client_payload.community_branch || inputs.c>
+        uses: softprops/action-gh-release@v1
+        with:
+          files: |
+            ${{ env.ISO_PATH }}
+            ${{ env.ISO_PATH }}.md5
+            ${{ env.ISO_PATH }}.pkgs
+            ${{ steps.prepare-iso.outputs.release_name }}.z*
+          tag_name: ${{ github.event.client_payload.release_tag || inputs.release_tag }}
+          name: ${{ steps.prepare-iso.outputs.release_name }}
+          generate_release_notes: true
 
diff --git a/action.yml b/action.yml
--- a/action.yml
+++ b/action.yml
@@ -14,6 +14,9 @@ outputs:
   iso_path:
     description: "Path to the generated ISO file"
     value: ${{ steps.build.outputs.iso_path }}
+  xz_path:
+    description: "Path to the generated TAR.XZ file"
+    value: ${{ steps.build.outputs.xz_path }}
   release_name:
     description: "Name of the release"
     value: ${{ steps.prepare-iso.outputs.release_name }}
@@ -196,4 +199,35 @@ runs:
           fi
           popd
         }
-        build_mkroot_fs
+
+        cleanup_and_move_files() {
+          #OUTPUT_ISO_PATH_NAME=$(find /var/cache/manjaro-tools/iso -type f -name "*.iso" -exec stat -c '%Y %n' {} + | sort -nr | awk 'NR==1 {print $2}')
+          #FILE_PKG=$(find /var/cache/manjaro-tools/iso -type f -name "*-pkgs.txt" -exec stat -c '%Y %n' {} + | sort -nr | awk 'NR==1 {print $2}')
+          OUTPUT_ISO_PATH_NAME=$(find "$WORK_PATH/void-mklive" -type f -name "*.iso" -printf '%T@ %p\n' | sort -nr | head -n 1 | cut -d' ' -f2-)
+          OUTPUT_XZ_PATH_NAME=$(find "$WORK_PATH/void-mklive" -type f -name "*.tar.xz" -printf '%T@ %p\n' | sort -nr | head -n 1 | cut -d' ' -f2-)
+          ISO_BASENAME=$(basename "$OUTPUT_ISO_PATH_NAME")
+          XZ_BASENAME=$(basename "$OUTPUT_XZ_PATH_NAME")
+
+          echo "OUTPUT_ISO_PATH_NAME=$OUTPUT_ISO_PATH_NAME" >> "$GITHUB_ENV"  # Exporta OUTPUT_ISO_PATH_NAME para outras etapas
+          echo "OUTPUT_XZ_PATH_NAME=$OUTPUT_XZ_PATH_NAME" >> "$GITHUB_ENV"  # Exporta OUTPUT_ISO_PATH_NAME para outras etapas
+          echo "OUTPUT_ISO_PATH_NAME: $OUTPUT_ISO_PATH_NAME"
+          echo "OUTPUT_XZ_PATH_NAME: $OUTPUT_XZ_PATH_NAME"
+
+          mv -fv "$OUTPUT_XZ_PATH_NAME" "$WORK_PATH/" || echo "Failed to move tar.xz file"
+          echo "iso_path=$WORK_PATH/$ISO_BASENAME" >> "$GITHUB_OUTPUT"
+          echo "xz_path=$WORK_PATH/$XZ_BASENAME" >> "$GITHUB_OUTPUT"
+        }
+
+        main() {
+          build_mkroot_fs
+          cleanup_and_move_files
+        }
+
+        main
+
+    - name: Set ISO path
+      shell: bash
+      run: |
+        echo "ISO_PATH=$WORK_PATH/$ISO_BASENAME" >> $GITHUB_ENV
+        echo "XZ_PATH=$WORK_PATH/$XZ_BASENAME" >> $GITHUB_ENV
+
